### ISSUE TITLE
Complete rework due to changed requirements

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#23]
A complete rework of the back- and frontend is necessary due to functional and nonfunctional requirement changes.
New nonfunctional requirements:
- An intuitive UX so that normal people can understand and gets shown the workflow to use the tool
- simple and bug free

New functional requirements:
- 

Required code changes:
- [ ] rename `questions` to `qualityModel`

to be continued...

**Comment by ciearius** [comment]
We can go ahead and make the best of this tragedy 😜 by switching to [Prisma](https://prisma.io) and and a restrictive and precise data-model.

**Comment by ciearius** [comment]
We should also discuss about how we keep our logs and mb do research on the current approach about consequences and bottlenecks such as but not limited to: 
- does this have performance drawbacks?
- does this make a difference storage wise? (I hear log files can get ridiculously large \*cough\* \*cough\*)

As pointed out previously: this enumeration is inconclusive.

**Comment by GeneralMine** [comment]
we already on our way implementing it 🚀
