### ISSUE TITLE
Optimization of SSR

### ISSUE THREAD

**Issue by ciearius** [GeneralMine/S2QUAT#26]
We have left one opportunity open to optimize the querying of data while server-side rendering pages! 
In svelte-kit there is a hook named `serverFetch` which allows to influence where requests are being sent. By implementing a simple replace in this hook we might be able to prevent hitting our firewall, load-balancing and even the nginx server! 

See the [svelte kit docs](https://kit.svelte.dev/docs#hooks-serverfetch)

**Comment by GeneralMine** [comment]
Now implemented? @ciearius

**Comment by ciearius** [comment]
Yes! e3bf98af4feeaee9f14b5cf4d94168f8eb4c7127
