### ISSUE TITLE
Auth cookie doesnt get passed to load() -> using onMount instead

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#27]
I encountered the following problem mentioned here: https://github.com/sveltejs/kit/issues/672
Which is still open here: https://github.com/sveltejs/kit/issues/1777

After authentication I tried to fetch data inside of load(). 
But unfortunately this doesnt work due to the problem that the auth cookie with our token wont get passed through. 

So using load is useless.

That bug is also mentioned here: https://youtu.be/bG7cxwBMVag?t=2841
Its suggested to use onMount instead to fetch authorized data.

**Comment by GeneralMine** [comment]
Solved with some nasty hacks

**Comment by ciearius** [comment]
well they're not THAT nasty 😇
