### ISSUE TITLE
Deploy new approach

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#36]

**Comment by GeneralMine** [comment]
@ciearius there is an error with dependencies while trying to deploy. A local `npm run dev` works fine. All packages are installed and updated
Any idea?
![image](https://user-images.githubusercontent.com/33132009/124588090-b5971d80-de58-11eb-876d-2f02bd0f5430.png)

**Comment by ciearius** [comment]
I've read in an official issue, that an update might fix this [see the official issue](https://github.com/sveltejs/kit/issues/763). This might be loosely linked.

**Comment by GeneralMine** [comment]
Thanks but we're already using the latest version.
```
"devDependencies": {
    "@sveltejs/adapter-node": "next",
    "@sveltejs/kit": "next",
```
I still dont know how to fix this :(

**Comment by GeneralMine** [comment]
Well I fixed that error above by using `npm run build` in advance to preview.
Now its the same error our docker containers are getting:
![image](https://user-images.githubusercontent.com/33132009/124599423-f21d4600-de65-11eb-8a66-4392fbd8dafd.png)

**Comment by GeneralMine** [comment]
solved by moving some packages to dependencies
