### ISSUE TITLE
Auth middleware for every endpoint

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#37]
Every endpoint has to make sure that the user is authenticated!
Either we find a nice way to define a middleware or we define an util which will be called for every endpoint.

Or maybe using hooks is enough? In a video someone said that that will be enough, but I dont know..

This one is for you my dear ;)

**Comment by ciearius** [comment]
The approach here differs massively from the one on sapper. Since middlewares are no longer a thing we'll have to be satisfied with something more redundant (and with "we" I mean "you" 👀).

**Comment by ciearius** [comment]
Will implement a solution today.

**Comment by ciearius** [comment]
**This is how you use it**
```js
import {isAuthenticatedAs, politely_ask_to_back_off, roles} from "$lib/authLib";
```

```js
if(!isAuthenticatedAs(user, roles.ADMIN) {
    return politely_ask_to_back_off(); // alternatively just return nothing
}
```

Any objections or suggestions?

**Comment by GeneralMine** [comment]
There is still an issue in the code:
![image](https://user-images.githubusercontent.com/33132009/124586432-b5961e00-de56-11eb-8be9-020c70a971c2.png)

Did you already tested that in some endpoint?

**Comment by GeneralMine** [comment]
implemented
