### ISSUE TITLE
Warning: Unsupported node engine/version

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#50]
While building the docker image I got that error:
![image](https://user-images.githubusercontent.com/33132009/125418704-4b73e745-707f-48d2-b5c7-d25b90e5b21e.png)

What do you suggest @ciearius ? Should be upgrade our docker images to Node 16?

**Comment by ciearius** [comment]
Yes. We need to use one of the node versions matching those seen there.

**Comment by GeneralMine** [comment]
I was wondering, because the latest node docker image wasnt part of the required versions. But it seems like they updated it recently. Thanks @ciearius
