### ISSUE TITLE
Implement list pages for survey responses

### ISSUE THREAD

**Issue by GeneralMine** [GeneralMine/S2QUAT#59]

**Comment by GeneralMine** [comment]
@ciearius is it possible to somehow reactively refresh that each block?
![image](https://user-images.githubusercontent.com/33132009/126297378-d5e99f1b-5674-4a18-9459-6a7d163c087a.png)

`from` and `to` are both updated inside their binding in `Table`, but the `each` wont refresh the entries

**Comment by GeneralMine** [comment]
![image](https://user-images.githubusercontent.com/33132009/126299156-33f689fa-0463-4a0a-a6b3-a98e92d23781.png)
That isn't working either. The console log is working, but the `each` block wont update

**Comment by ciearius** [comment]
Bear in mind:

https://stackoverflow.com/questions/63372044/svelte-each-loop-is-not-updated-while-object-changed-dynamically

**Comment by GeneralMine** [comment]
I know, I'm not changing its values, I'm updating the entire object:
`$: tableEntries = updateList(from, to);`
or
`$: tableEntries = survey.responses.slice(from, to)`

for this:
`{#each tableEntries as response}`

with fully working console logging using:
`$: console.log(tableEntries);`

So its only the each thats not working

**Comment by GeneralMine** [comment]
Or does using `$:` wont trigger the update on `each`?

**Comment by ciearius** [comment]
( ͡° ͜ʖ ͡°)
```js
// weirdo toggles the table
weirdo = false;
Promise.resolve().then(() => {
    weirdo = true;
});
```
Hacky solution to force refresh a table with each.
