### ISSUE TITLE
Privacy statement doesn't include use of Google Analytics

### ISSUE THREAD

**Issue by miku86** [GeneralMine/S2QUAT#66]
Hey folks, 

the [privacy statement](https://s2quat.raiser.dev/privacy) does not include Google Analytics, although it is used:

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JXTTW8TCDY"></script>
```

Source: [1](https://www.datenschutz.de/google-analytics-und-aehnliche-dienste-nur-mit-einwilligung-nutzbar/)

Solution1: [2](https://www.datenschutzexperte.de/google-analytics-und-datenschutz/#c11194)
Solution2: Do not use it.

Greetings
Michael

**Comment by GeneralMine** [comment]
@miku86 Thank you for your privacy concerns.
I removed Google Analytics in the newest release!

Thanks for the support!
